# Generated by Django 3.1.7 on 2022-04-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(verbose_name='Название для запроса')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=15, verbose_name='Ник')),
                ('image', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('about_me', models.TextField(max_length=2000, verbose_name='О себе')),
                ('rating', models.CharField(max_length=30, verbose_name='Рейтинг игрока')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game', verbose_name='Игра')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='')),
                ('lose', models.IntegerField(verbose_name='Поражений')),
                ('win', models.IntegerField(verbose_name='Побед')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='api.profile', verbose_name='Капитан')),
                ('games', models.ManyToManyField(to='api.Game', verbose_name='Игры')),
                ('players', models.ManyToManyField(related_name='team_players', to='api.Profile', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game', verbose_name='Игра')),
                ('teams', models.ManyToManyField(to='api.Team', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
