# Generated by Django 3.1.7 on 2022-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='team', to='api.Profile', verbose_name='Игроки'),
        ),
    ]
