# Generated by Django 3.1.7 on 2022-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220518_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=3000, verbose_name='Новость')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
