# Generated by Django 3.1.7 on 2022-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220520_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('logo', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('rating', models.CharField(max_length=30, verbose_name='Рейтинг игрока')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('game', models.CharField(max_length=100, verbose_name='Игра')),
                ('about_me', models.TextField(max_length=2000, verbose_name='О себе')),
                ('league', models.CharField(max_length=200, verbose_name='Лига')),
                ('player', models.BooleanField(verbose_name='Статус')),
                ('nickname', models.CharField(max_length=30, verbose_name='Никнэйм')),
                ('document', models.ImageField(upload_to='', verbose_name='Документ удостоверяющий личность')),
            ],
            options={
                'verbose_name': 'Заявка на создание профиля',
                'verbose_name_plural': 'Заявки на создание профиля',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('finish', models.TimeField(verbose_name='Окончание')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('game', models.CharField(max_length=50, verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Заявка на прохождение тренировки',
                'verbose_name_plural': 'Заявки на прохождение тренировки',
            },
        ),
    ]
